esphome:
  name: proto-4
  friendly_name: Proto 4
  
#external_components:
# - source: github://stas-sl/esphome-sound-level-meter  # add @tag if you want to use a specific version (e.g @v1.0.0)

esp32:
  board: m5stack-atom
  framework:
    type: arduino
    version: latest
#api:
#  encryption:
#    key: WMjV9JHFm2Tb50iXrgM5bwya3ai35HunXeFrYf4RYaE=

wifi:
  networks:
  - ssid: !secret wifi_ssid_mobile
    password: !secret wifi_password_mobile
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  - ssid: !secret wifi_ssid_megan
    password: !secret wifi_password_megan
  ap:
    ssid: "tell your WiFi said hi PROTO-4"

logger:

mqtt:
  broker: 192.168.1.95
  username: zack
  password: Xuj27tk0p!
  topic_prefix: proto/proto-4
  on_message:
    - topic: proto/proto-4/status
      payload: 'online'
      then:
        - light.turn_on:
            id: led
            effect: pulse
            color_mode: RGB
            red: 0%
            green: 0%
            blue:  100%
            brightness: 1%
    - topic: proto/proto-4/binary_sensor/button/state
      payload: 'ON'
      then:
        - light.toggle:
            id: chandelier
    - topic: proto/proto-4/binary_sensor/button/state
      payload: 'HELD'
      then:
        - light.turn_on:
            id: chandelier
            effect: WLED
            brightness: 100%

ota:

captive_portal:

improv_serial:

wled:
  
#i2s_audio:
#  i2s_lrclk_pin: GPIO33
#  i2s_bclk_pin: GPIO19


      

#microphone:
#  - platform: i2s_audio
#    id: echo_microphone
#    i2s_din_pin: GPIO23
#    adc_type: external
#    pdm: true

#voice_assistant:
#  microphone: echo_microphone
#  on_start:
#    - light.turn_on:
#        id: led
#        blue: 100%
#        red: 0%
#        green: 0%
#        effect: none
#  on_tts_start:
#    - light.turn_on:
#        id: led
#        blue: 0%
#        red: 0%
#        green: 100%
#        effect: none
#  on_tts_end:
#    - media_player.play_media: !lambda return x;
#    - light.turn_on:
#        id: led
#        blue: 0%
#        red: 0%
#        green: 100%
#        effect: pulse
#  on_end:
#    - delay: 1s
#    - wait_until:
#        not:
#          media_player.is_playing: media_out
#    - light.turn_off: led
#  on_error:
#    - light.turn_on:
#        id: led
#        blue: 0%
#        red: 100%
#        green: 0%
#        effect: none
#    - delay: 1s
#    - light.turn_off: led
script:
  - id: send_message
    then:
    - repeat:
        count: 5
        then:
          - mqtt.publish:
              topic: proto/proto-3/display
              payload: "party"
          - delay: 500ms
          - mqtt.publish:
              topic: proto/proto-3/display
              payload: "time"
          - delay: 500ms
          - mqtt.publish:
              topic: proto/proto-3/display2
              payload: "cool"
          - delay: 500ms
          - mqtt.publish:
              topic: proto/proto-3/display2
              payload: "guys"
          - delay: 500ms
    - mqtt.publish:
        topic: proto/proto-3/display
        payload: ""
        retain: True
    - mqtt.publish:
        topic: proto/proto-3/display2
        payload: ""
        retain: True
    - mqtt.publish:
        topic: proto/proto-3/display-text-off
        payload: "off"
        retain: False
        
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
    name: Button
    id: echo_button
    on_multi_click:
      - timing:
          - ON FOR 0s to 1s
        then:
          - script.execute: send_message
      - timing:
          - ON FOR 1s to 5s
        then:
          - mqtt.publish:
              topic: proto/proto-4/binary_sensor/button/state
              payload: "HELD"
      - timing:
          - ON FOR AT LEAST 5s
        then:
          - mqtt.publish:
              topic: proto/proto-4/binary_sensor/button/state
              payload: "HELDLONG"

sensor:
  - platform: wifi_signal
    name: Wifi signal
    update_interval: 2min
  - platform: uptime
    name: Uptime
    update_interval: 2min
#  - platform: homeassistant
#    name: ha_water_power
#    entity_id: sensor.water_pump_power
#    id: ha_water_power
#  - platform: homeassistant
#    name: ha_phone_battery
#    entity_id: sensor.zack_s_phone_battery_level
#    id: ha_phone_battery
#  - platform: homeassistant
#    name: ha_hot_air
#    entity_id: sensor.shellymotion2_8cf681a1fa80_temperature
#    id: ha_hot_air

text_sensor:
  - platform: wifi_info
    ssid:
      name: SSID
      update_interval: 2min
  - platform: wifi_info
    ip_address:
      name: IP Address

#    on_multi_click:
#      - timing:
#          - ON FOR AT MOST 350ms
#          - OFF FOR AT LEAST 10ms
#        then:
#          - mqtt.publish:
#              topic: proto-4/button/get
#              payload: "Button Pressed! Old test. dont worry about this"
#      - timing:
#          - ON FOR AT LEAST 350ms
#        then:
#          - voice_assistant.start:
#      - timing:
#          - ON FOR AT LEAST 350ms
#          - OFF FOR AT LEAST 10ms
#        then:
#          - voice_assistant.stop:

#media_player:
#  - platform: i2s_audio
#    id: media_out
#    name: Media Player
#    dac_type: external
#    i2s_dout_pin: GPIO22
#    mode: mono

output:

  - platform: ledc
    pin: GPIO32
    id: gpio_32
    channel: 2
    max_power: 100%
    min_power: 32%


light:

  - platform: monochromatic
    output: gpio_32
    name: Chandelier_internal
    id: chandelier_internal
    internal: True
    effects:
      - random:
          transition_length: 1000ms
          update_interval: 1000ms
      - flicker:
          alpha: 100%
          intensity: 1%
      - flicker:
          name: Lantern
          alpha: 100%
          intensity: .2%
      - strobe:
      - pulse:
          transition_length: 2000ms
          update_interval: 2000ms    

  - platform: partition
    name: "Chandelier"
    id: chandelier
    segments:
      - single_light_id: chandelier_internal
    effects:
      - wled:
          port: 1337
    
  - platform: esp32_rmt_led_strip
    id: led
    name: None
    pin: GPIO27
    default_transition_length: 0s
    chipset: SK6812
    num_leds: 1
    rgb_order: grb
    rmt_channel: 0
    effects:
      - random:
          transition_length: 1000ms
          update_interval: 1000ms
      - flicker:
      - strobe:
      - pulse:
          transition_length: 2000ms
          update_interval: 2000ms


        