esphome:
  name: "proto-2"
  friendly_name: Proto 2

esp32:
  board: esp32dev
  framework:
    type: arduino



# Enable logging
logger:

debug:

external_components:
  - source:
      type: git
      url: https://github.com/u-fire/ESPHomeComponents/

# no need for api or wifi block when using just ESP-Now
now_mqtt:

# Enable Home Assistant API
#api:
#  encryption:
#    key: "CAgTcJVmSBgNKcQWx8bSWqd2n1BVg14sOXXaxBVvrng="

#ota:
#  password: "a624597cd9052dce02d596bc9f691b56"

#wled:

#web_server:
#  port: 6969
#  local: True

#mqtt:
#  broker: zackshouse.duckdns.org
#  username: zack
#  password: 
#  topic_prefix: proto/proto-2

#  on_message:
#    - topic: proto/proto-2/status
#      payload: 'online'
#      then:
#        - light.turn_on:
#            id: red_led
#            effect: strobe

#wifi:
#  networks:
#  - ssid: !secret wifi_ssid
#    password: !secret wifi_password
#  - ssid: !secret wifi_ssid_mobile
#    password: !secret wifi_password_mobile
#  - ssid: !secret wifi_ssid_megan
#    password: !secret wifi_password_megan

  # Enable fallback hotspot (captive portal) in case wifi connection fails
#  ap:
#    ssid: "tell your WiFi said hi PROTO-2"
  
#captive_portal:


#time:
#  - platform: homeassistant
#    id: homeassistant_time

output:
  - platform: ledc
    pin: GPIO4
    id: gpio_4
    channel: 2
    max_power: 20%

  - platform: ledc
    pin:
      number: GPIO33
      inverted: True
    id: gpio_33

light:
  - platform: monochromatic
    output: gpio_4
    name: LED
    id: led
    effects:
      - random:
          transition_length: 100ms
          update_interval: 100ms
      - flicker:
          alpha: 95%
          intensity: 10%
      - strobe:
      - pulse:
          transition_length: 4000ms
          update_interval: 4000ms     
        
  - platform: monochromatic
    output: gpio_33
    name: Red LED
    id: red_led
    effects:
      - random:
          transition_length: 100ms
          update_interval: 100ms
      - flicker:
          alpha: 95%
          intensity: 10%
      - strobe:
      - pulse:
          transition_length: 4000ms
          update_interval: 4000ms     

  - platform: partition
    name: "Partition Light 1"
    id: partition_light_1
    segments:
      - single_light_id: led
    effects:
#      - wled:
      - random:
          transition_length: 100ms
          update_interval: 100ms
      - flicker:
          alpha: 95%
          intensity: 10%
      - strobe:
      - pulse:
          transition_length: 4000ms
          update_interval: 4000ms     
 


sensor:

  - platform: uptime
    name: Uptime

  - platform: internal_temperature
    name: "Internal Temperature"

  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"

text_sensor:
  - platform: version
    name: ESP Version

switch:      
  - platform: restart
    name: Restart
